Allow specifying environment variables independently
truenas/scale-build pull request #161
Opened 2021-06-06 13:28 UTC by sonicaj

This commit adds changes to allow specifying enviornment variables independently for each package. This is helpful to avoid influence of one env variable meant for a specific package on another which might result in changed behavior when it builds.

2021-06-06 13:28 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110934

2021-06-06 13:28 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110934

2021-06-06 13:29 UTC, sonicaj commented
ok to test

2021-06-07 10:56 UTC, themylogin requested changes

2021-06-07 10:56 UTC, themylogin commented on scale_build/packages/build.py
> +                    if all(f(env_var['key']) != env_var['value'] for f in (os.environ.get, self.env.get)):
You forgot `APT_ENV` here.
Can we make a single method that will construct resulting `env` for command and check against it instead?

2021-06-07 16:46 UTC, themylogin approved these changes

2021-06-07 16:49 UTC, merged