Update iso.py
truenas/scale-build pull request #339
Opened 2022-09-06 17:08 UTC by q5sys

Joe should be discussing this PR with Waqar.

This will allow us to automate the shasum checking in our jenkins pipline since the shasum file will now be made so that we can use `shasum -c ` to verify its correct once the push has happened.
![image](https://user-images.githubusercontent.com/4654247/188697143-afc530ce-64b0-42bd-8861-d4711de76ca9.png)

2022-09-06 17:19 UTC, sonicaj requested changes

2022-09-06 17:19 UTC, sonicaj commented on scale_build/image/iso.py
> +            ['sha256sum', os.path.join(RELEASE_DIR, f'TrueNAS-SCALE-{get_image_version()}.iso')], log=False).stdout.replace("./tmp/release/", ""))
Use `.replace(f'{RELEASE_DIR}/', '').strip()` instead please

2022-09-06 17:19 UTC, q5sys commented on scale_build/image/iso.py
> +            ['sha256sum', os.path.join(RELEASE_DIR, f'TrueNAS-SCALE-{get_image_version()}.iso')], log=False).stdout.replace("./tmp/release/", ""))
wilco

2022-09-06 17:24 UTC, sonicaj approved these changes
Thanks! ( do test please before merging )

2022-09-06 17:25 UTC, sonicaj reviewed
Hmm flake8 is failing, can you confirm please if everything is in order ( indent etc ) ?

2022-09-06 17:31 UTC, q5sys commented
ah its line length... `./scale_build/image/iso.py:167:121: E501 line too long (155 > 120 characters)`

2022-09-06 17:48 UTC, sonicaj approved these changes

2022-09-07 14:19 UTC, q5sys commented
Build is good and sum file is formed correctly
![image](https://user-images.githubusercontent.com/4654247/188901822-bb9890bf-b4a5-4d5c-9363-254240e21b38.png)

2022-09-12 17:38 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118141

2022-09-12 17:39 UTC, merged