`intel-gpu-tools` and cleaning `/var/trash`
truenas/scale-build pull request #675
Opened 2024-08-01 19:06 UTC by creatorcary

This is a 2-for-1:

- [NAS-130356](https://ixsystems.atlassian.net/browse/NAS-130356): Adding `intel-gpu-tools` package at community request.
- [NAS-130351](https://ixsystems.atlassian.net/browse/NAS-130351): Cleaning out `/var/trash` package diversions.

Passed all tests except `test_system_general_ui_rollback.test_system_general_ui_rollback`.
http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1760/

2024-08-01 19:10 UTC, aiden3c approved these changes

2024-08-01 19:26 UTC, creatorcary commented on scale_build/clean.py
> +    shutil.rmtree(DIVERT_DIR, ignore_errors=True)
I think this is failing silently. Will have to investigate.

2024-08-01 19:34 UTC, yocalebo requested changes
Please don't combine tickets. Each ticket needs to be kept separate from one another especially since they're fixing unrelated issues.

This allows us to more easily do git blame, git log and git revert in the event we need to revert something.

2024-08-01 20:46 UTC, yocalebo approved these changes

2024-08-02 12:46 UTC, merged

2024-08-02 12:46 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.